---
- name: Ensure git is installed
  become: true
  apt:
    pkg: "git"
    state: present
  when: ansible_os_family == "Debian"

- name: Make Vim directory
  become_user: "{{ vundle_user }}"
  file:
    path: "{{ vundle_config_dir }}"
    state: directory

- name: Make Vim bundle directory
  become_user: "{{ vundle_user }}"
  file:
    path: "{{ vundle_config_dir }}/bundle"
    state: directory

- name: Clone vundle
  become_user: "{{ vundle_user }}"
  git:
    repo: "{{ vundle_repo }}"
    dest: "{{ vundle_config_dir }}/bundle/Vundle.vim"
    accept_hostkey: "no"
    version: "master"

- name: Install Vim plugins
  become_user: "{{ vundle_user }}"
  shell: vim -E -s -u ~/.vimrc '+silent! PluginInstall' +qall
  tags:
    - skip_ansible_lint

- name: Run PluginClean
  become_user: "{{ vundle_user }}"
  shell: vim -E -s -u ~/.vimrc '+PluginClean!' +qall
